#!/bin/sh
# auth0-password-grant - programmatically retrieve an Auth0 access token using the password grant
VERSION=1.0.4

USER_NAME=
PASSWORD=
AUTH_URL=
CLIENT_ID=
REALM=
AUDIENCE=

CONFIG_PATH="$HOME/.config/auth0-password-grant"

if [ -e "$CONFIG_PATH" -a -x "$CONFIG_PATH" ]
then
  . "$CONFIG_PATH/config"
fi

while getopts "vCBXu:p:a:c:r:d:" opt
do
  case "$opt" in
    v)  echo "auth0-password-grant version $VERSION"
        exit 0
        ;;
    C)  "$EDITOR" "$CONFIG_PATH/config"
        exit 0
        ;;
    B)  BEARER=1
        ;;
    X)  CLIP=1
        ;;
    u)  USER_NAME="$OPTARG"
        ;;
    p)  PASSWORD="$OPTARG"
        ;;
    a)  AUTH_URL="$OPTARG"
        ;;
    c)  CLIENT_ID="$OPTARG"
        ;;
    r)  REALM="$OPTARG"
        ;;
    d)  AUDIENCE="$OPTARG"
        ;;
    *)  exit 1
        ;;
  esac
done

REPLY=$(curl -X POST \
  "https://$AUTH_URL/oauth/token" \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{ 
    "grant_type": "http://auth0.com/oauth/grant-type/password-realm",
    "username": "'"$USER_NAME"'",
    "password": "'"$PASSWORD"'",
    "audience": "'"$AUDIENCE"'",
    "scope": "openid email",
    "client_id":"'"$CLIENT_ID"'",
    "realm":"'"$REALM"'" 
}' 2>/dev/null)

TOKEN=$(echo "$REPLY" | jq '.access_token' | sed 's/"//g')
if [ -z "$TOKEN" -o "$TOKEN" = null ]
then
  echo "Error: failed to retrieve access token."
  echo -e "Details: $REPLY"
  exit 1
fi

if [ "$BEARER" ]
then
  TOKEN="Bearer $TOKEN"
fi

if [ "$CLIP" ]
then
  if [ $(command -v xclip) ]; then echo -n "$TOKEN" | xclip -selection clipboard
  elif [ $(command -v pbcopy) ]; then echo -n "$TOKEN" | pbcopy
  else
    echo "No suitable application to copy to clipboard found."
  fi
fi

echo "$TOKEN"
