.TH auth0-password-grant 5 "FEBRUARY 2018" 1.0.6 "User Manuals"
.SH NAME
auth0-password-grant/config - the user-specific configuration file

.SH DESCRIPTION
The
.B auth0-password-grant/config
file specifies request parameters for retrieving an access token through the Auth0 Resource Owner Password Grant. The file is sourced by
.BR auth0-password-grant (1)
at the beginning, before any options are parsed.

The parameters are:
.IP -
username (e.g., johndoe@example.com)
.IP -
password
.IP -
Auth0 hostname (e.g., example.auth0.com)
.IP -
client ID
.IP -
realm
.IP -
audience
.RE

Other parameters have been assigned reasonable defaults in the source code for
.BR auth0-password-grant (1).
Edit the shell script for fine-tuning.

Parameters should be specified in name-value pairs using POSIX variable assignments. Their names are respectively
.BR "USER_NAME, PASSWORD, AUTH_URL, CLIENT_ID, REALM " and " AUDIENCE" .

.SH EXAMPLES
.B USER_NAME=johndoe@example.com
.br
.B PASSWORD=123456
.br
.B AUTH_URL=example.auth0.com
.br
.B CLIENT_ID=q93JHMb49f1j103jh2D1HD24g
.br
.B REALM=default
.br
.B AUDIENCE=https://myservice.example.com/

.SH AUTHOR
.MT igorsowinski.mail@\:gmail.com
Igor Sowinski
.ME

.SH COPYRIGHT
Copyright \[u00A9] 2018 Igor Sowinski.  Licensed under the 3-clause BSD license.

.SH "SEE ALSO"
.BR auth0-password-grant (1)

